import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { setTimeout as delay } from "node:timers/promises";

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

import { ReaperApiReference } from "../src/mcp/reaper-docs-reference.js";

const generatedReference = [
  "<html><head><title>REAPER API functions</title></head><body>",
  "<font size=1>Generated by REAPER v7.73/macOS-arm64</font>",
  '<a name="GetMediaItemInfo_Value"><hr></a><br>',
  '<div class="l_func"><span>Lua: </span><code><i>number</i> reaper.GetMediaItemInfo_Value(<i>MediaItem</i> item, <i>string</i> parmname)</code><br><br></div>',
  "Get media item numerical-value attributes.<br>",
  "B_MUTE : bool * : muted (item solo overrides).<br>",
  "C_LANEPLAYS : char * : whether a fixed lane item plays.<br><br>",
  '<a name="GetMediaItemTake_Source"><hr></a><br>',
  '<div class="l_func"><span>Lua: </span><code><i>PCM_source</i> reaper.GetMediaItemTake_Source(<i>MediaItem_Take</i> take)</code><br><br></div>',
  "Get media source of media item take<br><br>",
  "</body></html>",
].join("\n");

test("REAPER API reference describes an exact Lua function from generated documentation", () => {
  const reference = ReaperApiReference.fromGeneratedHtml(generatedReference);

  assert.equal(reference.reaperVersion, "7.73/macOS-arm64");
  assert.deepEqual(reference.describeApi("GetMediaItemInfo_Value"), {
    name: "GetMediaItemInfo_Value",
    luaSignature: "number reaper.GetMediaItemInfo_Value(MediaItem item, string parmname)",
    description: [
      "Get media item numerical-value attributes.",
      "B_MUTE : bool * : muted (item solo overrides).",
      "C_LANEPLAYS : char * : whether a fixed lane item plays.",
    ].join("\n"),
    truncated: false,
  });
});

test("REAPER API reference bounds unusually long single-function descriptions", () => {
  const longDescription = "x".repeat(10_000);
  const reference = ReaperApiReference.fromGeneratedHtml(generatedReference.replace(
    "Get media source of media item take",
    longDescription,
  ));

  const entry = reference.describeApi("GetMediaItemTake_Source");
  assert.equal(entry?.description.length, 4_000);
  assert.equal(entry?.truncated, true);
});

test("REAPER API reference searches generated descriptions without returning the whole document", () => {
  const reference = ReaperApiReference.fromGeneratedHtml(generatedReference);

  assert.deepEqual(reference.search("muted lane", 5), [{
    name: "GetMediaItemInfo_Value",
    luaSignature: "number reaper.GetMediaItemInfo_Value(MediaItem item, string parmname)",
    excerpt: "B_MUTE : bool * : muted (item solo overrides).\nC_LANEPLAYS : char * : whether a fixed lane item plays.",
  }]);
});

async function answerDocsGenerate(runtimeRoot: string, generatedRoot: string): Promise<void> {
  const readyRoot = join(runtimeRoot, "bridge/main/commands/ready");
  let filename: string | undefined;
  for (let attempt = 0; attempt < 200; attempt += 1) {
    try {
      filename = (await readdir(readyRoot))[0];
    } catch {
      // The server creates the bridge spool lazily on refresh.
    }
    if (filename) break;
    await delay(5);
  }
  if (!filename) throw new Error("REAPER docs MCP did not submit a generate command");
  const command = JSON.parse(await readFile(join(readyRoot, filename), "utf8")) as {
    readonly command_id: string;
    readonly operation: string;
    readonly payload: unknown;
  };
  assert.equal(command.operation, "docs.generate");
  assert.deepEqual(command.payload, {});
  const heartbeatRoot = join(runtimeRoot, "bridge/main");
  await mkdir(heartbeatRoot, { recursive: true });
  await writeFile(join(heartbeatRoot, "heartbeat.json"), JSON.stringify({
    schema: "rma.bridge-heartbeat/v1",
    bridge_instance_id: "main",
    protocol_version: 1,
    observed_at: new Date().toISOString(),
    reaper_version: "7.73/macOS-arm64",
    project_id: "fixture-project",
    project_change_count: 0,
    state: "idle",
    active_command_id: null,
  }));
  await writeFile(join(generatedRoot, "reascripthelp.html"), generatedReference);
  const receiptRoot = join(runtimeRoot, "bridge/main/receipts");
  await mkdir(join(receiptRoot, "tmp"), { recursive: true });
  await mkdir(join(receiptRoot, "ready"), { recursive: true });
  const receipt = {
    schema: "rma.bridge-receipt/v1",
    protocol_version: 1,
    command_id: command.command_id,
    status: "succeeded",
    started_at: new Date().toISOString(),
    finished_at: new Date().toISOString(),
    artifacts: [],
    warnings: [],
    error: null,
    result: {
      fileName: "reascripthelp.html",
      reaperVersion: "7.73/macOS-arm64",
      tempDirectory: generatedRoot,
    },
  };
  const temporary = join(receiptRoot, "tmp", filename);
  await writeFile(temporary, JSON.stringify(receipt));
  await rename(temporary, join(receiptRoot, "ready", filename));
}

test("REAPER docs MCP refreshes, searches, and describes the locally generated API reference", async (context) => {
  const root = await mkdtemp(join(tmpdir(), "rma-reaper-docs-mcp-"));
  const generatedRoot = join(root, "system-tmp");
  const runtimeRoot = join(root, "runtime");
  const configPath = join(root, "local.toml");
  await mkdir(generatedRoot, { recursive: true });
  await writeFile(configPath, [
    "[paths]",
    `reaper_executable = ${JSON.stringify(join(root, "REAPER.app"))}`,
    `ffmpeg_executable = ${JSON.stringify(join(root, "ffmpeg"))}`,
    `reaper_resource_path = ${JSON.stringify(join(root, "REAPER"))}`,
    `runtime_root = ${JSON.stringify(runtimeRoot)}`,
    `audio_work_root = ${JSON.stringify(join(root, "audio"))}`,
    "",
    "[network]",
    'daemon_host = "127.0.0.1"',
    "daemon_port = 32180",
    'dsh_host = "127.0.0.1"',
    "dsh_port = 3080",
    "",
    "[llm.default]",
    'provider = "fixture"',
    'model = "fixture-model"',
    "",
    "[llm.mix_planner]",
    'provider = "fixture"',
    'model = "fixture-model"',
    "",
    "[llm.providers.fixture]",
    'display_name = "Fixture"',
    'api = "openai-completions"',
    'base_url = "https://example.invalid/v1"',
    'api_key_env = "FIXTURE_API_KEY"',
    "",
    "[[llm.providers.fixture.models]]",
    'id = "fixture-model"',
    "",
    "[reaper]",
    "poll_interval_ms = 10",
    "command_timeout_ms = 1000",
    "render_timeout_ms = 1000",
    "",
    "[safety]",
    "allow_network_audio_upload = false",
    "allow_source_media_write = false",
    "allow_gui_coordinate_control = false",
    "",
  ].join("\n"));

  const childEnvironment = Object.fromEntries(
    Object.entries(process.env).filter((entry): entry is [string, string] => entry[1] !== undefined),
  );
  childEnvironment.TMPDIR = generatedRoot;
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: ["--import=tsx", join(process.cwd(), "src/mcp/reaper-docs-server.ts"), "--config", configPath],
    cwd: process.cwd(),
    env: childEnvironment,
    stderr: "pipe",
  });
  const client = new Client({ name: "reaper-docs-contract", version: "1.0.0" });
  context.after(async () => {
    await client.close();
    await rm(root, { recursive: true, force: true });
  });
  await client.connect(transport);

  assert.deepEqual((await client.listTools()).tools.map((tool) => tool.name).sort(), [
    "describe_api",
    "refresh",
    "search",
    "status",
  ]);
  const statusCall = await client.callTool({ name: "status", arguments: {} });
  assert.equal(statusCall.isError, undefined, JSON.stringify(statusCall));
  assert.deepEqual(statusCall.structuredContent, {
    schema: "rma.reaper-docs-status/v1",
    ready: false,
  });

  const fakeBridge = answerDocsGenerate(runtimeRoot, generatedRoot);
  const refreshed = await client.callTool({ name: "refresh", arguments: {} });
  await fakeBridge;
  assert.equal((refreshed.structuredContent as { readonly ready: boolean }).ready, true);
  assert.equal((refreshed.structuredContent as { readonly reaperVersion: string }).reaperVersion, "7.73/macOS-arm64");

  const search = await client.callTool({ name: "search", arguments: { query: "muted lane", limit: 5 } });
  assert.deepEqual(search.structuredContent, {
    schema: "rma.reaper-docs-search/v1",
    reaperVersion: "7.73/macOS-arm64",
    results: [{
      name: "GetMediaItemInfo_Value",
      luaSignature: "number reaper.GetMediaItemInfo_Value(MediaItem item, string parmname)",
      excerpt: "B_MUTE : bool * : muted (item solo overrides).\nC_LANEPLAYS : char * : whether a fixed lane item plays.",
    }],
  });
  const described = await client.callTool({
    name: "describe_api",
    arguments: { name: "GetMediaItemTake_Source" },
  });
  assert.deepEqual(described.structuredContent, {
    schema: "rma.reaper-api-entry/v1",
    reaperVersion: "7.73/macOS-arm64",
    entry: {
      name: "GetMediaItemTake_Source",
      luaSignature: "PCM_source reaper.GetMediaItemTake_Source(MediaItem_Take take)",
      description: "Get media source of media item take",
      truncated: false,
    },
  });

  await writeFile(join(runtimeRoot, "bridge/main/heartbeat.json"), JSON.stringify({
    schema: "rma.bridge-heartbeat/v1",
    bridge_instance_id: "main",
    protocol_version: 1,
    observed_at: new Date().toISOString(),
    reaper_version: "7.74/macOS-arm64",
    project_id: "fixture-project",
    project_change_count: 0,
    state: "idle",
    active_command_id: null,
  }));
  assert.deepEqual((await client.callTool({ name: "status", arguments: {} })).structuredContent, {
    schema: "rma.reaper-docs-status/v1",
    ready: false,
    reason: "stale",
    cachedReaperVersion: "7.73/macOS-arm64",
    activeReaperVersion: "7.74/macOS-arm64",
  });
  assert.equal((await client.callTool({ name: "search", arguments: { query: "media" } })).isError, true);
});
