export interface ReaperApiEntry {
  readonly name: string;
  readonly luaSignature: string;
  readonly description: string;
  readonly truncated: boolean;
}

export interface ReaperApiSearchResult {
  readonly name: string;
  readonly luaSignature: string;
  readonly excerpt: string;
}

interface ParsedReaperApiEntry {
  readonly name: string;
  readonly luaSignature: string;
  readonly description: string;
}

const descriptionLimit = 4_000;

function decodeHtml(value: string): string {
  return value
    .replace(/&nbsp;/giu, " ")
    .replace(/&amp;/giu, "&")
    .replace(/&lt;/giu, "<")
    .replace(/&gt;/giu, ">")
    .replace(/&quot;/giu, '"')
    .replace(/&#39;/giu, "'");
}

function plainText(value: string): string {
  return decodeHtml(value
    .replace(/<br\s*\/?\s*>/giu, "\n")
    .replace(/<[^>]+>/gu, ""))
    .split("\n")
    .map((line) => line.replace(/[ \t]+/gu, " ").trim())
    .filter(Boolean)
    .join("\n");
}

function apiName(value: string): string {
  if (!/^[A-Za-z_][A-Za-z0-9_]{0,127}$/u.test(value)) {
    throw new Error("REAPER API name is invalid");
  }
  return value;
}

export class ReaperApiReference {
  readonly reaperVersion: string;
  readonly #entries: ReadonlyMap<string, ParsedReaperApiEntry>;

  private constructor(reaperVersion: string, entries: ReadonlyMap<string, ParsedReaperApiEntry>) {
    this.reaperVersion = reaperVersion;
    this.#entries = entries;
  }

  public static fromGeneratedHtml(source: string): ReaperApiReference {
    const version = /Generated by REAPER v([^<]+)/iu.exec(source)?.[1]?.trim();
    if (!version || version.length > 100) throw new Error("document is not a REAPER-generated API reference");
    const anchors = [...source.matchAll(/<a name="([A-Za-z_][A-Za-z0-9_]{0,127})"><hr><\/a><br>/gu)];
    const entries = new Map<string, ParsedReaperApiEntry>();
    for (const [index, anchor] of anchors.entries()) {
      const name = apiName(anchor[1]!);
      const start = anchor.index! + anchor[0].length;
      const end = anchors[index + 1]?.index ?? source.length;
      const block = source.slice(start, end);
      const lua = /<div class="l_func">[\s\S]*?<code>([\s\S]*?)<\/code>[\s\S]*?<\/div>/u.exec(block)?.[1];
      if (!lua) continue;
      const description = plainText(block.replace(/<div class="[celp]_func">[\s\S]*?<\/div>/gu, ""));
      const luaSignature = plainText(lua);
      if (luaSignature.length > 2_000) throw new Error("REAPER API signature exceeds the supported limit");
      entries.set(name, {
        name,
        luaSignature,
        description,
      });
    }
    if (entries.size === 0) throw new Error("REAPER-generated API reference has no Lua functions");
    return new ReaperApiReference(version, entries);
  }

  public describeApi(name: string): ReaperApiEntry | undefined {
    const entry = this.#entries.get(apiName(name));
    if (!entry) return undefined;
    return {
      name: entry.name,
      luaSignature: entry.luaSignature,
      description: entry.description.slice(0, descriptionLimit),
      truncated: entry.description.length > descriptionLimit,
    };
  }

  public search(query: string, limit: number): ReaperApiSearchResult[] {
    const normalized = query.trim().toLocaleLowerCase("en-US");
    if (normalized.length === 0 || normalized.length > 200) {
      throw new Error("REAPER API search query must contain 1 to 200 characters");
    }
    if (!Number.isInteger(limit) || limit < 1 || limit > 20) {
      throw new Error("REAPER API search limit must be between 1 and 20");
    }
    const terms = normalized.split(/\s+/u);
    const matches: Array<ReaperApiSearchResult & { readonly score: number }> = [];
    for (const entry of this.#entries.values()) {
      const haystack = `${entry.name}\n${entry.luaSignature}\n${entry.description}`.toLocaleLowerCase("en-US");
      if (!terms.every((term) => haystack.includes(term))) continue;
      const matchingLines = entry.description
        .split("\n")
        .filter((line) => terms.some((term) => line.toLocaleLowerCase("en-US").includes(term)))
        .slice(0, 4);
      matches.push({
        name: entry.name,
        luaSignature: entry.luaSignature,
        excerpt: matchingLines.join("\n").slice(0, 1200),
        score: entry.name.toLocaleLowerCase("en-US").includes(normalized) ? 0 : 1,
      });
    }
    return matches
      .sort((left, right) => left.score - right.score || left.name.localeCompare(right.name))
      .slice(0, limit)
      .map(({ score: _score, ...entry }) => entry);
  }
}
