import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface InstallBridgeOptions {
  readonly reaperResourcePath: string;
  readonly runtimeRoot: string;
  readonly audioWorkRoot: string;
  readonly bridgeInstanceId: string;
  readonly sourcePath: string;
  readonly workerSourcePath: string;
}

export interface InstalledBridge {
  readonly bridgeScriptPath: string;
  readonly launcherScriptPath: string;
  readonly renderWorkerScriptPath: string;
}

function luaString(value: string): string {
  return `"${value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\r", "\\r")
    .replaceAll("\n", "\\n")}"`;
}

export async function installBridge(options: InstallBridgeOptions): Promise<InstalledBridge> {
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(options.bridgeInstanceId)) {
    throw new TypeError("bridge instance id must be a filename-safe identifier");
  }

  const scriptsDirectory = join(options.reaperResourcePath, "Scripts", "REAPER Mixing Agent");
  const bridgeScriptPath = join(scriptsDirectory, "MixingAgentBridge.lua");
  const launcherScriptPath = join(scriptsDirectory, "StartMixingAgentBridge.lua");
  const renderWorkerScriptPath = join(scriptsDirectory, "RenderWorker.lua");
  await mkdir(scriptsDirectory, { recursive: true });
  await copyFile(options.sourcePath, bridgeScriptPath);
  await copyFile(options.workerSourcePath, renderWorkerScriptPath);

  const launcher = [
    "-- Generated by mixing-agent bridge install. Re-run install after local config changes.",
    'local section = "reaper_mixing_agent"',
    `reaper.SetExtState(section, "runtime_root", ${luaString(options.runtimeRoot)}, true)`,
    `reaper.SetExtState(section, "artifact_root", ${luaString(options.audioWorkRoot)}, true)`,
    `reaper.SetExtState(section, "bridge_instance_id", ${luaString(options.bridgeInstanceId)}, true)`,
    `dofile(${luaString(bridgeScriptPath)})`,
    "",
  ].join("\n");
  await writeFile(launcherScriptPath, launcher, "utf8");

  return { bridgeScriptPath, launcherScriptPath, renderWorkerScriptPath };
}
